### ISSUE TITLE
babbel2anki unusable

### ISSUE THREAD

**Issue by grac-zh** [pavelgordon/babbel2anki-chrome-extension#11]
after trying again and again to make the chrome extension babbel2anki work, i finally detected the main flaw: 
the author doesn't even understand the meaning of anki's front and backside of a card.
the translation of a word is entered in a field called "extra info" instead of "answer".
therefore anki can't detect both sides of a word: original and translation.

verdict: babbel2anki is USELESS, unless the author learns how anki works!

**Comment by pavelgordon** [comment]
Thanks for the constructive and friendly feedback. This extension is perfectly capable of rendering both frond and back side of both types of cards, I tested it once some. 
You can name fields differently, Extra Info, Answer, Translation. They will be displayed the same.
