### ISSUE TITLE
Only retrieves 200 entries and stops

### ISSUE THREAD

**Issue by jeff-kilbride** [pavelgordon/babbel2anki-chrome-extension#3]
Thanks for this extension! I would really like to get it working...

![image](https://user-images.githubusercontent.com/14877960/90997077-58aeb380-e575-11ea-9bb6-e5d87d651157.png)

As you can see, I have 2835 words in my Babbel vocabulary list. After installing the extension, the first time I loaded the Review Manager and hit the "Sync with Anki" button, the extension downloaded 200 of the words -- everything contained in the "__interceptedData" div. Unfortunately, I can't get it to download any more. I've tried paging through the Review Manager and manually clicking the "Sync with Anki" button several times. I've also tried setting the "Auto-sync to Anki" option to true and letting it sit for a few minutes. Nothing seems to work.

I've never coded a Chrome Extension, however looking at the code and the output in Chrome DevTools, it looks like the "__interceptedData" div is only getting set once when the Review Manager is first loaded. It seems like "__interceptedData" should update each time you change pages in the Review Manager, so each page of data can be synced to Anki. Otherwise, new words will only be synced when the first page of the Review Manager changes -- which is not very often, in my case.

Please let me know if I am doing something wrong or if there is a workaround. I am happy to help in whatever way I can, so if you need any information from me, please feel free to ask.

**Comment by pavelgordon** [comment]
Hey! First of all, thank you for the detailed description of an error! It's really helpful. 

I have identified a problem and pushed a fix for it. Could you please reinstall the extension and see if it fixes the problem for you?
Background: sometimes(not in 100% of cases) i loaded dictionary too early, when page was not yet fully loaded, and totalVocabularyCount was 0 instead of being equal to full vocabulary size(in your case 2835). then it was failing over to default value which is 200.

**Comment by jeff-kilbride** [comment]
Thanks for the quick reply! I thought it might be a timing issue, so I ran through the commands in the `xhrOverrideScript` manually in the console and was able to load some more vocabulary.

I downloaded your updated code. The first time I ran it, the one-second timer ran twice and then I got the following output in the console:

`fetched learning items/total vocabulary size 10 / 2835`

and there were 10 items in the `interceptedData` div. However, I've restarted Chrome and reloaded the Review Manager a few times and it seems to be working each time, now. Unfortunately, there is another issue. It looks like Babbel limits the number of vocabulary words and phrases to a maximum of 1000 displayed at a time:

![image](https://user-images.githubusercontent.com/14877960/91080564-999cdb80-e5fa-11ea-86fa-55201ac4a591.png)

I found the same issue when I was running the commands manually in the console. I could only get it to load 1000 items. I am able to page forward 1000 items at a time, but the `interceptedData` div is never updated. So, I manually ran the commands to update `interceptedData` in the console:

![image](https://user-images.githubusercontent.com/14877960/91082103-00bb8f80-e5fd-11ea-95e1-9d3ce86b757f.png)

This correctly updates the `interceptedData` div with the new page of vocabulary. However, when I run the manual sync again, I get a different error:

![image](https://user-images.githubusercontent.com/14877960/91082555-af5fd000-e5fd-11ea-84e9-7264fefb2c39.png)

The line of code being referenced is in the `sendDataToAnki` function:

```js
chrome.storage.sync.set({lastSyncedAmount: response.totalNotes})
```

The `response` object is undefined. Not really sure what is causing this. (Maybe the AnkiConnect connection can't be re-used?) I've been able to load about 1500 words into Anki, but I'm stuck on the 1000 item limit and the paging issue, now.

One suggestion I have is this:  instead of trying to load all the vocabulary at once, just let the user set the page size -- maximum of 100 -- and refresh the `interceptedData` div after each new page. You should be able to use the `WebRequest.onCompleted()` event to tell when the data needs to be updated. The user can then manually sync each page to Anki. It's a little more tedious than doing it all at once, but it's easier to understand what is happening. The sync also happens faster on a smaller data set. When I synced 1000 items, it took almost 10 minutes to update Anki. Doing a big data set like that is faster in one shot, but it probably **feels** faster doing it page by page.

**Comment by pavelgordon** [comment]
Yeah, I agree that Babbel has a limit of 1000 items per vocabulary. It's a good idea to not overload Babbel API and introduce paging.  That was on my todo-list.

I'll try to fix it today or tomorrow

**Comment by pavelgordon** [comment]
Well, more likely this weekend :) Just got free.

**Comment by pavelgordon** [comment]
Hey @jeff-kilbride, new version is pushed. I reworked fetching new words from babbel, and now you can load them page by page. Also, I disabled auto sync for now, it needs rework too.

**Comment by jeff-kilbride** [comment]
@pavelgordon  Thanks! The paging is working, but I'm still getting an error after more than one successful sync:

![Screen Shot 2020-08-29 at 12 23 10](https://user-images.githubusercontent.com/14877960/91644597-6e4b2f80-e9f2-11ea-91e9-b373b17c1c1a.png)

It seems once the Anki connection is used, it's not resetting properly.

**Comment by pavelgordon** [comment]
Hmm, it works on my machine with multiple sync.  Which version of AnkiConnect are you using?

**Comment by jeff-kilbride** [comment]
Actually, it doesn't look like a connection problem. It looks like there may be a parsing problem. I was able to narrow it down to a single page of 10 items:

<img width="1290" alt="Screen Shot 2020-08-29 at 12 58 58" src="https://user-images.githubusercontent.com/14877960/91645153-9721f380-e9f7-11ea-9992-2103c13dd3c8.png">

I get the error each time I try to sync this page. It looks like the last entry on this page is missing an image. Would that cause a problem?

**Comment by jeff-kilbride** [comment]
It's definitely the missing image. I searched each of these terms and synced them individually. The only one giving an error is the last one:  "Where is the next bus stop?"

**Comment by pavelgordon** [comment]
I will fix this in code, but could you please also report this missing image problem to Babbel? I am sure they would be happy to fix their dictionary :)

**Comment by jeff-kilbride** [comment]
@pavelgordon I just pushed a pull request that fixes the image problem and also allows for custom tags to be added in the popup window. Feel free to take what you want from it.

The extension works great, now. Thanks for all your work on this!

You can close this issue when you're ready.

![image](https://user-images.githubusercontent.com/14877960/91676920-29102600-eaf6-11ea-96e1-9b42d8902958.png)

**Comment by pavelgordon** [comment]
Thanks for help! Glad that someone else finds it useful besides me. Желаю удачи (good luck - but since you have 6k words you probably know that already :)
